# Heavily based on https://www.cloudreach.com/en/insights/blog/containerize-this-how-to-use-php-apache-mysql-within-docker-containers/
version: "3.2"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
       CTI_IMAGE_DIRECTORY: ${CTI_IMAGE_DIRECTORY}
    networks:
      - backend
    environment:
      DB_CONNECTION: "pgsql:host=db;port=5432;dbname=${DB_NAME}"
      DB_USER: "${DB_USERNAME}"
      DB_PASSWORD_FILE: /run/secrets/db_password
      CTI_IMAGE_DIRECTORY: ${CTI_IMAGE_DIRECTORY}
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
      - images:${CTI_IMAGE_DIRECTORY}
    container_name: php
    secrets:
      - db_password
  auth:
    build: 
      context: './keycloak/'
    networks:
      - backend
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
    container_name: auth
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - db
      - auth
    networks:
      - frontend
      - backend
    ports:
      - "90:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: apache
  db:
    build:
      context: './db/'
      args:
       POSTGRES_VERSION: ${POSTGRES_VERSION}
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./db/scripts:/docker-entrypoint-initdb.d
    networks:
      - backend
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    container_name: db
    secrets:
      - db_password
  java:
    build:
      context: './java/'
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend
    container_name: java
networks:
  frontend:
  backend:
volumes:
    data:
    images:
secrets:
  db_password:
    file: ./db/dev_password.txt