\connect TICKET_RECOGNITION

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM appuser;
GRANT SELECT,UPDATE,INSERT,DELETE ON ALL TABLES IN SCHEMA public TO appuser;

CREATE SEQUENCE TICKET_ID_SEQ START 1;
CREATE TABLE TICKET (
    ID BIGINT NOT NULL DEFAULT nextval('TICKET_ID_SEQ'),
    TICKET_TEMPLATE_ID BIGINT NOT NULL ,
    TOUR_ID BIGINT NOT NULL ,
    SCAN_DATE TIMESTAMP NOT NULL ,
    PRIMARY KEY (ID)
);
ALTER SEQUENCE TICKET_ID_SEQ OWNED BY TICKET.ID;

CREATE SEQUENCE TICKET_TEMPLATE_ID_SEQ START 1;
CREATE TABLE TICKET_TEMPLATE (
    ID BIGINT NOT NULL DEFAULT nextval('TICKET_TEMPLATE_ID_SEQ'),
    KEY VARCHAR(50) NOT NULL UNIQUE,
    IMAGE_FILE_EXTENSION VARCHAR(10) NOT NULL,
    TOUR_OPERATOR_ID BIGINT NOT NULL ,
    PRIMARY KEY (ID)
);
ALTER SEQUENCE TICKET_TEMPLATE_ID_SEQ OWNED BY TICKET_TEMPLATE.ID;

CREATE SEQUENCE TEXT_DEFINITION_ID_SEQ START 1;
CREATE TABLE TEXT_DEFINITION (
    ID BIGINT NOT NULL DEFAULT nextval('TEXT_DEFINITION_ID_SEQ'),
    TICKET_TEMPLATE_ID BIGINT NOT NULL ,
    KEY VARCHAR(50) NOT NULL ,
    DESCRIPTION VARCHAR(100) NOT NULL ,
    X int NOT NULL ,
    Y int NOT NULL ,
    WIDTH int NOT NULL ,
    HEIGHT int NOT NULL ,
    PRIMARY KEY (ID),
    UNIQUE (TICKET_TEMPLATE_ID, KEY)
);
ALTER SEQUENCE TEXT_DEFINITION_ID_SEQ OWNED BY TEXT_DEFINITION.ID;

CREATE SEQUENCE TOUR_OPERATOR_ID_SEQ START 1;
CREATE TABLE TOUR_OPERATOR (
    ID BIGINT NOT NULL DEFAULT nextval('TOUR_OPERATOR_ID_SEQ'),
    NAME VARCHAR(100) NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);
ALTER SEQUENCE TOUR_OPERATOR_ID_SEQ OWNED BY TOUR_OPERATOR.ID;

CREATE SEQUENCE TOUR_ID_SEQ START 1;
CREATE TABLE TOUR (
    ID BIGINT NOT NULL DEFAULT nextval('TOUR_ID_SEQ'),
    DESCRIPTION VARCHAR(100) NOT NULL ,
    CODE int NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);
ALTER SEQUENCE TOUR_ID_SEQ OWNED BY TOUR.ID;

CREATE TABLE TOUR_TOUR_POSITION (
    TOUR_ID BIGINT NOT NULL,
    TOUR_POSITION_ID BIGINT NOT NULL ,
    PRIMARY KEY (TOUR_ID, TOUR_POSITION_ID)
);

CREATE SEQUENCE TOUR_POSITION_ID_SEQ START 1;
CREATE TABLE TOUR_POSITION (
    ID BIGINT NOT NULL DEFAULT nextval('TOUR_POSITION_ID_SEQ'),
    DESCRIPTION VARCHAR(100) NOT NULL ,
    CODE int NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);
ALTER SEQUENCE TOUR_POSITION_ID_SEQ OWNED BY TOUR_POSITION.ID;

CREATE SEQUENCE TICKET_POSITION_ID_SEQ START 1;
CREATE TABLE TICKET_POSITION (
    ID BIGINT NOT NULL DEFAULT nextval('TICKET_POSITION_ID_SEQ'),
    DESCRIPTION VARCHAR(100) NOT NULL ,
    CODE int NOT NULL,
    TICKET_ID int NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (ID, CODE)
);
ALTER SEQUENCE TICKET_POSITION_ID_SEQ OWNED BY TICKET_POSITION.ID;

ALTER TABLE TICKET ADD CONSTRAINT fk_TICKET_TICKET_TEMPLATE_ID FOREIGN KEY(TICKET_TEMPLATE_ID)
REFERENCES TICKET_TEMPLATE (ID);

ALTER TABLE TICKET ADD CONSTRAINT fk_TICKET_TOUR_ID FOREIGN KEY(TOUR_ID)
REFERENCES TOUR (ID);

ALTER TABLE TICKET_TEMPLATE ADD CONSTRAINT fk_TICKET_TEMPLATE_TOUR_OPERATOR_ID FOREIGN KEY(TOUR_OPERATOR_ID)
REFERENCES TOUR_OPERATOR (ID);

ALTER TABLE TEXT_DEFINITION ADD CONSTRAINT fk_TEXT_DEFINITION_TICKET_TEMPLATE_ID FOREIGN KEY(TICKET_TEMPLATE_ID)
REFERENCES TICKET_TEMPLATE (ID);

ALTER TABLE TOUR_TOUR_POSITION ADD CONSTRAINT fk_TOUR_TOUR_POSITION_TOUR_ID FOREIGN KEY(TOUR_ID)
REFERENCES TOUR (ID);

ALTER TABLE TOUR_TOUR_POSITION ADD CONSTRAINT fk_TOUR_TOUR_POSITION_TOUR_POSITION_ID FOREIGN KEY(TOUR_POSITION_ID)
REFERENCES TOUR_POSITION (ID);

ALTER TABLE TICKET_POSITION ADD CONSTRAINT fk_TICKET_POSITION_TICKET_ID FOREIGN KEY(TICKET_ID)
REFERENCES TICKET (ID);
