CREATE DATABASE TICKET_RECOGNITION;

USE TICKET_RECOGNITION;

CREATE TABLE `TICKET` (
    `ID` BIGINT  NOT NULL AUTO_INCREMENT,
    `TICKET_TEMPLATE_ID` BIGINT  NOT NULL ,
    `TOUR_ID` BIGINT  NOT NULL ,
    `SCAN_DATE` DATETIME  NOT NULL ,
    PRIMARY KEY (
        `ID`
    )
);

CREATE TABLE `TICKET_TEMPLATE` (
    `ID` BIGINT  NOT NULL AUTO_INCREMENT,
    `KEY` VARCHAR(50)  NOT NULL UNIQUE,
    `TOUR_OPERATOR_ID` BIGINT  NOT NULL ,
    PRIMARY KEY (
        `ID`
    )
);

CREATE TABLE `TEXT_DEFINITION` (
    `ID` BIGINT  NOT NULL AUTO_INCREMENT,
    `TICKET_TEMPLATE_ID` BIGINT  NOT NULL ,
    `KEY` VARCHAR(50)  NOT NULL ,
    `DESCRIPTION` VARCHAR(100)  NOT NULL ,
    `X` int  NOT NULL ,
    `Y` int  NOT NULL ,
    `WIDTH` int  NOT NULL ,
    `HEIGHT` int  NOT NULL ,
    PRIMARY KEY (
        `ID`
    )
);

CREATE TABLE `TOUR_OPERATOR` (
    `ID` BIGINT  NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(100)  NOT NULL ,
    PRIMARY KEY (
        `ID`
    )
);

CREATE TABLE `TOUR` (
    `ID` BIGINT  NOT NULL AUTO_INCREMENT,
    `DESCRIPTION` VARCHAR(100)  NOT NULL ,
    `CODE` int  NOT NULL ,
    PRIMARY KEY (
        `ID`
    )
);

CREATE TABLE `TOUR_TICKET_POSITION` (
    `TOUR_ID` BIGINT  NOT NULL ,
    `TICKET_POSITION_ID` BIGINT  NOT NULL 
);

CREATE TABLE `TICKET_POSITION` (
    `ID` BIGINT  NOT NULL AUTO_INCREMENT,
    `DESCRIPTION` VARCHAR(100)  NOT NULL ,
    `CODE` int  NOT NULL ,
    PRIMARY KEY (
        `ID`
    )
);

ALTER TABLE `TICKET` ADD CONSTRAINT `fk_TICKET_TICKET_TEMPLATE_ID` FOREIGN KEY(`TICKET_TEMPLATE_ID`)
REFERENCES `TICKET_TEMPLATE` (`ID`);

ALTER TABLE `TICKET` ADD CONSTRAINT `fk_TICKET_TOUR_ID` FOREIGN KEY(`TOUR_ID`)
REFERENCES `TOUR` (`ID`);

ALTER TABLE `TICKET_TEMPLATE` ADD CONSTRAINT `fk_TICKET_TEMPLATE_TOUR_OPERATOR_ID` FOREIGN KEY(`TOUR_OPERATOR_ID`)
REFERENCES `TOUR_OPERATOR` (`ID`);

ALTER TABLE `TEXT_DEFINITION` ADD CONSTRAINT `fk_TEXT_DEFINITION_TICKET_TEMPLATE_ID` FOREIGN KEY(`TICKET_TEMPLATE_ID`)
REFERENCES `TICKET_TEMPLATE` (`ID`);

ALTER TABLE `TOUR_TICKET_POSITION` ADD CONSTRAINT `fk_TOUR_TICKET_POSITION_TOUR_ID` FOREIGN KEY(`TOUR_ID`)
REFERENCES `TOUR` (`ID`);

ALTER TABLE `TOUR_TICKET_POSITION` ADD CONSTRAINT `fk_TOUR_TICKET_POSITION_TICKET_POSITION_ID` FOREIGN KEY(`TICKET_POSITION_ID`)
REFERENCES `TICKET_POSITION` (`ID`);
